spring:
    application:
        name : sample-project    
    devtools:
        livereload:
            enabled:  true        
    thymeleaf:
        enabled : true
        cache : false
        prefix : classpath:templates/
        suffix : .html
        mode : HTML
        check-template-location : false
    datasource :
        url: jdbc:h2:mem:testdb;MODE=Oracle;DB_CLOSE_DELAY=-1;DATABASE_TO_UPPER=false
        username : sa
        password :
        driver-class-name : org.h2.Driver
    h2 :
        console :
            enabled : true
            path : /h2        